### ISSUE TITLE
Is all datasets in /data are supported ?

### ISSUE THREAD

**Issue by zhaohan-xi** [bknyaz/graph_nn#4]
Hi Dear Author,

This looks a very good implementation in using GCN for graph-level classification (may also called inductive). Besides the sample running you shown in jupyter notebook, are the other datasets are also supported in running? If yes, could I ask which part should modify to change the calling of datasets? Thanks!

**Comment by bknyaz** [comment]
Hi,
The DataReader class can in principle read any dataset in the TU format (see datasets here https://ls11-www.cs.tu-dortmund.de/staff/morris/graphkerneldatasets).
You need to download the dataset, put it in the `./data/` folder and change line `dataset = 'proteins'`.
But I think it's better to use the python script in my repo (https://github.com/bknyaz/graph_nn/blob/master/graph_unet.py), because I tested it more and for different datasets. It has the `--dataset` argument that you can use to specify any TU dataset.

**Comment by zhaohan-xi** [comment]
Got, thanks for response
